apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: auth
          image: devopszms2024/zms-devops-auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: auth-configmap
            - configMapRef:
                name: mongodb-auth-configmap
            - secretRef:
                name: mongodb-auth-secret
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-kafka.backend.svc.cluster.local:9092"
            - name: KAFKA_AUTH_PASSWORD
              value: "6DUnElt7GW"

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: backend
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: grpc
      port: 8001
      targetPort: 8001
