apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
  namespace: backend
data:
  SERVICE_PORT: "8080"
  IDENTITY_PROVIDER_HOST: "keycloak.backend.svc.cluster.local"
  BOOKING_HOST: "booking"
  BOOKING_PORT: "8001"
  KAFKA_BOOTSTRAP_SERVERS: "my-kafka.backend.svc.cluster.local:9092"
  KAFKA_AUTH_PASSWORD: "6DUnElt7GW"
  JAEGER_ENDPOINT: "http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces"
  LOKI_ENDPOINT: "http://loki.istio-system.svc.cluster.local:3100/api/prom/push"